#!/usr/bin/env bash
# display information about subdomains

output ()
{
    echo "The subdomain $1 is a $2 record and points to $3"
}
sub=('www' 'web-01' 'web-02' 'lb-01')
if [ "$#" -eq 2 ];then
    SUB_DOMAIN="$2"
    RECORD_TYPE=$(dig "$2".bestmedi.tech | grep -A1 'ANSWER SECTION:' | awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $4}')
    DESTINATION=$(dig "$2".bestmedi.tech | grep -A1 'ANSWER SECTION:' | awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $5}')
    output "$SUB_DOMAIN" "$RECORD_TYPE" "$DESTINATION"
elif [ "$#" -eq 1 ];then
    for element in "${sub[@]}"; do
    SUB_DOMAIN="$element"
    RECORD_TYPE=$(dig "$element".bestmedi.tech | grep -A1 'ANSWER SECTION:' | awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $4}')
    DESTINATION=$(dig "$element".bestmedi.tech | grep -A1 'ANSWER SECTION:' | awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $5}')
    output "$SUB_DOMAIN" "$RECORD_TYPE" "$DESTINATION"
    done
fi
