#!/usr/bin/env bash
# display information about subdomains

output ()
{
    echo "The subdomain $1 is a $2 record and points to $3"
}
if [ "$#" -eq 2 ];then
    SUB_DOMAIN="$2"
    RECORD_TYPE=$(awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $4}' /etc/hosts)
    DESTINATION=$(awk -v w1="$1" -v w2="$2" '$0 ~ w1 && $0 ~ w2 {print $5}' /etc/hosts)
    output "$SUB_DOMAIN" "$RECORD_TYPE" "$DESTINATION"
elif [ "$#" -eq 1 ]; then
    while IFS= read -r line; do
        if echo "$line" | grep -q "$1"; then
            SUB_DOMAIN=$(echo "$line" | awk -F'.' -v w1="$1" '$0 ~ w1 {print $1}')
            RECORD_TYPE=$(echo "$line" | awk -v w1="$1" '$0 ~ w1 {print $4}')
            DESTINATION=$(echo "$line" | awk -v w1="$1" '$0 ~ w1 {print $5}')
            output "$SUB_DOMAIN" "$RECORD_TYPE" "$DESTINATION"
        fi
    done < /etc/hosts
fi
