#!/usr/bin/env bash
#Install nginx web server with http header
sudo apt-get update
sudo apt-get install nginx -y
echo "server {
    listen 80 ;
    listen [::]:80;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
	add_header X-Served-By \$hostname always;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
