#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
file="/etc/passwd"
IFS=:
while IFS= read -r line
do
        fields=("$line")
        USERNAME="${fields[0]}"
        GROUP_ID="${fields[4]}"
        HOME_DIRECTORY="${fields[5]}"
        COMMAND="${fields[6]}"
        USERID="${fields[2]}"
        PASSWORD="${fields[1]}"
        USERIDINFO="${fields[3]}"
text="The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USERID place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
echo "$text"
done < "$file"
