#!/usr/bin/env bash
#configures an Ubuntu server  with localhost and facebook new ip
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' ~/hosts.new
sed -i '$a8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
